# Generated by Django 5.2.4 on 2025-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('max_capacity', models.PositiveIntegerField(default=200)),
                ('used_capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
